### ISSUE TITLE
The latest version can not create a new project

### ISSUE THREAD

**Issue by erich2s** [JustinPedersen/SpreadCounter#2]

**Comment by JustinPedersen** [comment]
Hey @EricH2S, thanks for spotting that! Will see if I can update and put out a fix for you sometime soon.

**Comment by JustinPedersen** [comment]
Heya @EricH2S, I've posted an update with a new compiled EXE too, please can you give it a test when you can. If its giving you any other problems just open another issue and I'll have a look. Thanks!
